// Command sprite-gen builds the embedded sprite dataset for internal/sprite.
//
// It downloads animated sprite source images for the full national Pokédex
// from PokeAPI/sprites (pinned at pinnedSpritesSHA, see fetch.go), composites
// and converts them into the compact spritedata.Bundle wire format, and
// writes the result to internal/sprite/data/sprites.gob.gz plus a generated
// Go name-lookup table at internal/sprite/registry_gen.go. Both outputs are
// meant to be committed — go build/goreleaser never need network access.
//
// Sprite artwork is © Nintendo/Creatures Inc./GAME FREAK; see /NOTICE.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/gob"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/GyeongHoKim/pokemon-cli/internal/sprite"
	"github.com/GyeongHoKim/pokemon-cli/internal/sprite/spritedata"
)

const (
	outputDataPath     = "internal/sprite/data/sprites.gob.gz"
	outputRegistryPath = "internal/sprite/registry_gen.go"
	previewFrameDelay  = 150 * time.Millisecond
)

func main() {
	preview := flag.String("preview", "", "animate the given species name in the terminal using the already-generated embedded data, instead of regenerating")
	flag.Parse()

	if *preview != "" {
		if err := runPreview(*preview); err != nil {
			log.Fatal(err)
		}
		return
	}

	if err := runGenerate(); err != nil {
		log.Fatal(err)
	}
}

// runPreview loops the species' animation frames in the terminal (clearing
// and reprinting each one) so compositing/subsampling can be eyeballed.
// Ctrl-C to stop.
func runPreview(name string) error {
	key, err := sprite.Resolve(name)
	if err != nil {
		return err
	}
	s, err := sprite.Load(key)
	if err != nil {
		return err
	}

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt)

	fmt.Print("\x1b[?25l") // hide cursor
	defer fmt.Print("\x1b[?25h")

	for i := 0; ; i++ {
		select {
		case <-sigCh:
			return nil
		default:
		}
		fmt.Print("\x1b[H\x1b[2J")
		fmt.Printf("=== %s: frame %d/%d ===\n%s\n", name, i%s.FrameCount()+1, s.FrameCount(), s.Render(i))
		time.Sleep(previewFrameDelay)
	}
}

func runGenerate() error {
	client := &http.Client{Timeout: httpTimeoutS * time.Second}

	fmt.Println("fetching national dex list...")
	entries, err := fetchDexList(client)
	if err != nil {
		return fmt.Errorf("fetch dex list: %w", err)
	}
	fmt.Printf("got %d species\n", len(entries))

	fmt.Println("fetching sprite sources (cached under .cache/sprite-src/)...")
	fetched, err := fetchAll(client, entries)
	if err != nil {
		return fmt.Errorf("fetch sprites: %w", err)
	}

	fmt.Println("converting sprites...")
	bundle := make(spritedata.Bundle, len(fetched))
	var surviving []dexEntry
	var skipped []int
	for i, f := range fetched {
		if f.GIF == nil {
			skipped = append(skipped, f.ID)
			continue
		}
		frames, err := decodeAnimatedSprite(f.GIF)
		if err != nil {
			return fmt.Errorf("species %d: decode animated sprite: %w", f.ID, err)
		}

		bundle[f.ID] = spritedata.SpeciesSprites{Frames: frames}
		surviving = append(surviving, entries[i])
	}
	fmt.Printf("converted %d species (%d skipped, no animated sprite: %v)\n", len(bundle), len(skipped), skipped)

	if err := writeBundle(bundle); err != nil {
		return fmt.Errorf("write bundle: %w", err)
	}
	if err := writeRegistry(surviving); err != nil {
		return fmt.Errorf("write registry: %w", err)
	}

	info, err := os.Stat(outputDataPath)
	if err == nil {
		fmt.Printf("wrote %s (%d bytes)\n", outputDataPath, info.Size())
	}
	fmt.Printf("wrote %s\n", outputRegistryPath)
	return nil
}

func writeBundle(bundle spritedata.Bundle) error {
	if err := os.MkdirAll(filepath.Dir(outputDataPath), 0o755); err != nil {
		return err
	}

	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	if err := gob.NewEncoder(gz).Encode(bundle); err != nil {
		return fmt.Errorf("gob encode: %w", err)
	}
	if err := gz.Close(); err != nil {
		return err
	}
	return os.WriteFile(outputDataPath, buf.Bytes(), 0o644)
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// normalizeKey mirrors internal/sprite's normalizeKey. Duplicated
// intentionally (see plan): a 3-line pure function isn't worth exporting
// just to share between the generator and the runtime package.
func normalizeKey(name string) string {
	return nonAlnum.ReplaceAllString(strings.ToLower(name), "")
}

func writeRegistry(entries []dexEntry) error {
	type kv struct {
		key string
		id  int
	}
	seen := make(map[string]bool)
	var kvs []kv
	for _, e := range entries {
		k := normalizeKey(e.Name)
		if seen[k] {
			continue
		}
		seen[k] = true
		kvs = append(kvs, kv{key: k, id: e.ID})
	}
	sort.Slice(kvs, func(i, j int) bool { return kvs[i].key < kvs[j].key })

	bySlugID := make([]dexEntry, len(entries))
	copy(bySlugID, entries)
	sort.Slice(bySlugID, func(i, j int) bool { return bySlugID[i].ID < bySlugID[j].ID })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/sprite-gen; DO NOT EDIT.\n\n")
	b.WriteString("package sprite\n\n")
	fmt.Fprintf(&b, "var nameToKey = map[string]Key{\n")
	for _, e := range kvs {
		fmt.Fprintf(&b, "\t%q: %d,\n", e.key, e.id)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "var keyToSlug = map[Key]string{\n")
	for _, e := range bySlugID {
		fmt.Fprintf(&b, "\t%d: %q,\n", e.ID, e.Name)
	}
	b.WriteString("}\n")

	return os.WriteFile(outputRegistryPath, []byte(b.String()), 0o644)
}
